config/routes.rb
Rails.application.routes.draw do
  get 'contact_us', to: 'contact_form#index', as: 'contact_us'

  get 'contact_form/new'
  post 'contact_form/create'
  get 'about_us', to: 'about#index', as: 'about_us'
  resources :partners
  resources :projects
  resources :ourservices
  
  get 'hysan', to: 'cpanel#index', as: 'hysan'
  resources :hero_images
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # get 'sessions/new'
  get 'signup', to: "users#new"
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hero_image.rb
class HeroImage < ApplicationRecord
  has_many_attached :images
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
    validates :subject, presence: true
    validates :body, presence: true
end

app/models/ourservice.rb
class Ourservice < ApplicationRecord
    has_many_attached :images
    has_many_attached :pdf_files
    belongs_to :user
    validates :Title, presence: true, length: { minimum: 5 }
    validates :description, presence: true, length: { minimum: 10 }

end

app/models/partner.rb
class Partner < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_secure_password
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    format: /\A\S+@\S+\z/

  has_many :hero_images
  has_many :ourservices
  has_many :projects
    def self.authenticate(email, password)
        user = User.find_by(email: email)
        user && user.authenticate(password)
    end

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def self.new_token
      SecureRandom.urlsafe_base64
    end

    def remember 
      self.remember_token = user.new_token
      update_attribute(:remember_digest)
    end


end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @hero_images = HeroImage.all.limit(2)
  end
end

app/controllers/cpanel_controller.rb
class CpanelController < ApplicationController
  before_action :require_signin
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @hero_images = HeroImage.all
    @ourservices = Ourservice.limit(4)
    @partners = Partner.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: %i[new create]
  before_action :require_correct_user, only: %i[edit update destroy]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'Thanks for signup!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Account updated successfuly!'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path, alert: 'Account successfully deleted!'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to root_path, alert: 'You are not authorized!' unless current_user?(@user)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/cpanel_helper.rb
module CpanelHelper
end

app/helpers/hero_images_helper.rb
module HeroImagesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ourservices_helper.rb
module OurservicesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<div class="about">
    <div class="about__header">
        <h6>We provide the best services. Need help?</h6>
        <h1>About Us</h1>
        <p>Trust, Integrity, Punctuality, Quality, to be Open, to be Kind, to be Role Model</p>
    </div>
    <div class="about__content">
       <div class="row">
           <div class="desktop-6 phone-12 tab-port-12">
                <div class="about_text">
                    <h5>We are increasing bussiness success with the technology</h5>
                        <p>The company was founded in 2015 in Tanzania by Tanzanians. It started as a supplier
                        of laboratory equipment, chemicals, consumables, personal protective equipment as
                        well as maintenance of the supplied items. But by 2017 it started selling raw materials
                        like Caustic soda flakes, Sodium hypochlorite, Common salts, etc. to the Food
                        industries like CCK, Bakheresa Food Products, Super Meal Food, Sayona Food
                        Products, Jambo Food Product, and Mega Beverage Limited.</p>

                        <p>
                        In 2023 the company moved its operations to Mkuranga which opened its own
blending and mixing plant and was previously held in the SIDO Industrial area -
Vingunguti.
                        </p>

                        <p> Now the company manufactures and supplies products with the initial name of
                        HYSAN – AD which is used as CIP, COP, Conveyor Lubrications, Utilities Chemicals,
                        WSP, WTP, and WSP, in addition, also provides services when you choose to use our
                        products.</p>

                        <p>To meet the needs of our customers the company is certified by ISO 9001:2015
                        Quality Management System and ISO 22000:2018 Food Safety System. and has also
                        undergone the process of the country's requirements to obtain recognition by
                        government institutions and authorities such as TBS, GLCA, OSHA, etc. </p>

                        <p>We are essential to our customers by providing the best products and 
                        services to help them achieve their aspirations.</p>

                        <p>Our unique approach to sourcing and supplying the highest quality, best value
                        products and brands, providing precisely what you need, exactly when and
                        where you need it.</p>

<p>We are committed to continuously building the company through our team's
dedication to the values of innovation, integrity, reliability, service and teamwork.</p>

                </div>
           </div>
            <div class="desktop-6 phone-12 tab-port-6">
                <div class="about_images">
                    <% @hero_images.each do |hero_image| %>
                        <% images = hero_image.images.limit(1) %>
                        <% images.each do |image| %>
                            <%= image_tag image, class: "about__img" %>
                        <% end %>
                    <% end %>
                </div>
            </div>
       </div>
    </div>

</div>

app/views/cpanel/index.html.erb
<div class="dashboard">
    <h2>Hello <%= current_user.email %></h2>
    <h3>Welcome to Control Panel</h3>
    <div class="row">
        <div class="desktop-6 tab-port-12 phone-12">
            <div class="container">
                <%= link_to "Upload Hero Image", new_hero_image_path, class: "btn btn--small btn--comp" %>
                <%= link_to "Add Services", new_ourservice_path, class: "btn btn--small btn--comp" %>
                <%= link_to "Add Projects", new_project_path, class: "btn btn--small btn--comp" %>
                <%= link_to "Add Partners", new_partner_path, class: "btn btn--small btn--comp" %>
                <%= button_to "Logout", logout_path, method: :delete, class: "btn btn--border" %>
            </div>
        </div>
    </div>
</div>

app/views/home/_slider.html.erb
<div class="tab-port-12 tab-land-12 phone-12 desktop-12">
    <div data-controller="slider" class="banner">
        <div class="slider">
            <% @hero_images.each do |hero_image| %>
                <% hero_image.images.each do |image| %>
                    <%= image_tag image, class: "slider__img" %>
                <% end %>
            <% end %>
        </div>
    
        <div class="overlay">
            <div class="row">
                <div class="desktop-12 tab-land-3 tab-port-3 phone-12">
                    <div class="banner__text">
                        <h1 class="banner-heading"> quality and comprehensive support.</h1>
                        <p>
                            Our unique approach to sourcing and supplying the highest quality, 
                            best value products and brands,
                            providing precisely what you need, exactly when and where you need it.
                        </p>
                       <div class="btn-group">
                            <%= button_to "Learn More", about_us_path, method: :get, class: "btn btn--main  btn--mob" %>
                       </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<section class="section">
    <%= render 'slider' %>
</section>
<section class="service-section">
    
    <%= render 'ourservices/grid' %>
</section>

<section class="why">
    <h1 class='why__title'>Why us</h1>
    <div class="row ">
        <div class="desktop-4 tab-port-2 tab-land-2 phone-12">
            <div class="why__card">
                <i class="fa-solid fa-screwdriver-wrench"></i>
                <div class="content">
                    <h4>TRUST</h4>
                    <p>
                    The work environment is open, honest, collaborative, and family-oriented.</p>
                </div>
            </div>
        </div>
        <div class="desktop-4 tab-port-2 tab-land-2 phone-12">
            <div class="why__card">
            <i class="fa-solid fa-money-check-dollar"></i>
                <div class="content">
                    <h4>INDIVIDUALITY</h4>
                    <p>HYG & SAN TECH COMPANY LTD deeply respect the knowledge, skills,
                    ideas, and capabilities that each employee brings to the team.</p>
                </div>
            </div>
        </div>
        <div class="desktop-4 tab-port-2 tab-land-2 phone-12">
            <div class="why__card">
            <i class="fa-solid fa-business-time"></i>
                <div class="content">
                    <h4>MORE YEARS OF EXPERINCE</h4>
                    <p>HYG & SAN TECH COMPANY LTD deeply respect the knowledge, skills,
                    ideas, and capabilities that each employee brings to the team. With a proven track record, our team bring deep industry knowledge and expertise, offering reliable solutions and insights honed over years of practice</p>
                </div>
            </div>
        </div>
        <div class="desktop-4 tab-port-2 tab-land-2 phone-12">
            <div class="why__card">
            <i class="fa-solid fa-phone-volume"></i>
                <div class="content">
                    <h4>CREATIVITY</h4>
                    <p>Our professionals are fountains of new ideas, fueling better products,
                    services, and processes. HYG & SAN TECH COMPANY LTD embraces
                    laughter, humor, and having fun while working toward a common goal.</p>
                </div>
            </div>
        </div>
        <div class="desktop-4 tab-port-2 tab-land-2 phone-12">
            <div class="why__card">
            <i class="fa-solid fa-medal"></i>
                <div class="content">
                    <h4> QUALITY</h4>
                    <p>HYG & SAN TECH COMPANY LTD employees always strive to produce
                    excellent work that pushes the company upward. They embrace their
                    responsibilities, enjoy the process of solving problems, and solutions and add
                    value to customers.
                    </p>
                </div>
            </div>
        </div>
        <div class="desktop-4 tab-port-2 tab-land-2 phone-12">
            <div class="why__card">
                <i class="fa-solid fa-truck-fast"></i>
                <div class="content">
                    <h4>LEADERSHIP</h4>
                    <p>Employees share the company’s vision and passion,</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="partners">
    <h4>OUR PARTNERS</h4>
    <div class="row">
    <% @partners.each do |partner| %>
        <div class="desktop-3 tab-port-6 tab-land-6 phone-4">
            <div class="partners__item">
                <%= image_tag partner.image, class: "partners__img" %>
            </div>
        </div>
    <% end %>
    </div>
</section>