config/routes.rb
Rails.application.routes.draw do
  get 'contact_us', to: 'contact_form#index', as: 'contact_us'

  get 'contact_form/new'
  post 'contact_form/create'
  get 'about_us', to: 'about#index', as: 'about_us'
  resources :partners
  resources :projects
  resources :ourservices
  
  get 'hysan', to: 'cpanel#index', as: 'hysan'
  resources :hero_images
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # get 'sessions/new'
  get 'signup', to: "users#new"
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hero_image.rb
class HeroImage < ApplicationRecord
  has_many_attached :images
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
    validates :subject, presence: true
    validates :body, presence: true
end

app/models/ourservice.rb
class Ourservice < ApplicationRecord
    has_many_attached :images
    has_many_attached :pdf_files
    belongs_to :user
    validates :Title, presence: true, length: { minimum: 5 }
    validates :description, presence: true, length: { minimum: 10 }

end

app/models/partner.rb
class Partner < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_secure_password
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    format: /\A\S+@\S+\z/

  has_many :hero_images
  has_many :ourservices
  has_many :projects
    def self.authenticate(email, password)
        user = User.find_by(email: email)
        user && user.authenticate(password)
    end

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def self.new_token
      SecureRandom.urlsafe_base64
    end

    def remember 
      self.remember_token = user.new_token
      update_attribute(:remember_digest)
    end


end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @hero_images = HeroImage.all.limit(2)
  end
end

app/controllers/cpanel_controller.rb
class CpanelController < ApplicationController
  before_action :require_signin
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @hero_images = HeroImage.all
    @ourservices = Ourservice.limit(4)
    @partners = Partner.all
  end
end

app/controllers/ourservices_controller.rb
class OurservicesController < ApplicationController
  before_action :set_ourservice, only: %i[ show edit update destroy ]

  # GET /ourservices or /ourservices.json
  def index
    @ourservices = Ourservice.all
  end

  # GET /ourservices/1 or /ourservices/1.json
  def show
  end

  # GET /ourservices/new
  def new
    @ourservice = Ourservice.new
  end

  # GET /ourservices/1/edit
  def edit
  end

  # POST /ourservices or /ourservices.json
  def create
    @ourservice = Ourservice.new(ourservice_params)
    @ourservice.user = current_user

    respond_to do |format|
      if @ourservice.save
        format.html { redirect_to hysan_path, notice: "Ourservice was successfully created." }
        format.json { render :show, status: :created, location: @ourservice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ourservice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ourservices/1 or /ourservices/1.json
  def update
    respond_to do |format|
      if @ourservice.update(ourservice_params)
        format.html { redirect_to hysan_path, notice: "This section was successfully updated." }
        format.json { render :show, status: :ok, location: @ourservice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ourservice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ourservices/1 or /ourservices/1.json
  def destroy
    @ourservice.destroy

    respond_to do |format|
      format.html { redirect_to ourservices_url, notice: "This item was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ourservice
      @ourservice = Ourservice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ourservice_params
      params.require(:ourservice).permit(:Title, :description, images: [], pdf_files: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: %i[new create]
  before_action :require_correct_user, only: %i[edit update destroy]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'Thanks for signup!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Account updated successfuly!'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path, alert: 'Account successfully deleted!'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to root_path, alert: 'You are not authorized!' unless current_user?(@user)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/cpanel_helper.rb
module CpanelHelper
end

app/helpers/hero_images_helper.rb
module HeroImagesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ourservices_helper.rb
module OurservicesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ourservices/_form.html.erb
<div class="form form--mid">
  <div class="form__container">
  <h2>Add service</h2>
<%= form_with(model: ourservice) do |form| %>
    <%= render "shared/errors", object: ourservice %>
    
  <div class="input-box">
    <%= form.text_field :Title, required: "required" %>
    <span>Title</span>
    <i></i>
  </div>

  <div class="input-box">
    <%= form.text_field:description, required: "required" %>
    <span>Description</span>
    <i></i>
  </div>

  <div class="input-box">
    <%= form.file_field :images, multiple: true, required: "required" %>
    <span>Upload Image</span>
    <i></i>
  </div>

  <div class="input-box">
  <%= form.file_field :pdf_files, multiple: true, required: "required" %>
  <span>Upload pdf files</span>
  <i></i>
</div>
      <%= form.submit "Upload", class: "btn btn--mid" %>
<% end %>
  </div>
</div>

app/views/ourservices/_grid.html.erb
<div class="service" id='service'>
    <h1>OUR SERVICES</h1>
    <div class="service__container">
        <div class="row">
        <% @ourservices.each do |service| %>
            <div class="desktop-3 tab-port-6 tab-land-6 phone-12">
                <div class="service__item">
                <%= link_to ourservice_path(service) do %>

            <% if service.images.attached? %>
                <%= image_tag rails_blob_path(service.images[0]), class: "service__img" %>
            <% end %>
            <div class="service__content">
                <h5 class="service__title">
                    <%= service.Title %>
                </h5>
                <p class="service__desc"><%= truncate(service.description, length: 140, separator: '') %></p>
            </div>
        <% end %>
                </div>
            </div>
        <% end %>
        </div>
    </div>
</div>

app/views/ourservices/_ourservice.html.erb
<div class="grid-container" data-controller="readmore">
  <div class="angry-grid">
  
    <div id="item-0">
       <div class="service-show__img">
       <% if ourservice.images.attached? %>
         <%= image_tag rails_blob_path(ourservice.images[0]), class: "slder__img" %>
       <% end %>
       </div>
    </div>
  
    <div id="item-1">
      <h1><%= ourservice.Title %></h1>
      <p><%= ourservice.description %></p>
    </div>
  
    <div id="item-2">
      <% if ourservice.images.attached? %>
      # <%= image_tag rails_blob_path(ourservice.images[1]), class: "slder__img" %>
      <% end %>
    </div>
  
    <div id="item-3">
      <% if ourservice.images.attached? %>
      <%= image_tag rails_blob_path(ourservice.images[2]), class: "slder__img" %>
      <% end %>
    </div>
  </div>
  <div class="pdf" >
    <% @ourservice.pdf_files.each do |pdf| %>
      <iframe src="<%= rails_blob_path(pdf, disposition: 'inline') %>#toolbar=0"  width="100%" height="600px" frameborder="1"></iframe>
    <% end %>
  </div>
</div>

app/views/ourservices/edit.html.erb
<h1>Editing ourservice</h1>

<%= render "form", ourservice: @ourservice %>

<br>

<div>
  <%= link_to "Show this ourservice", @ourservice %> |
  <%= link_to "Back to ourservices", ourservices_path %>
</div>

app/views/ourservices/index.html.erb
<%= render 'ourservices/grid' %>

app/views/ourservices/new.html.erb
<%= render "form", ourservice: @ourservice %>
<br>
<div>
  <%= link_to "Back to ourservices", ourservices_path %>
</div>

app/views/ourservices/show.html.erb
<div class="ourservice-details">
  <%= render @ourservice %>

  <strong class="created-by"> Created by <%= @ourservice.user.email %> </strong>
</div>
<%  if  current_user %>
<div class="actions">
  <%= link_to "Edit this page", edit_ourservice_path(@ourservice), class: "btn" %> |
  <%= link_to "Back to ourservices", ourservices_path, class: "btn" %>

  <%= button_to "Delete this page", @ourservice, method: :delete, class: "btn btn--danger" %>
</div>
<% end %>