config/routes.rb
Rails.application.routes.draw do
  get 'contact_us', to: 'contact_form#index', as: 'contact_us'

  get 'contact_form/new'
  post 'contact_form/create'
  get 'about_us', to: 'about#index', as: 'about_us'
  resources :partners
  resources :projects
  resources :ourservices
  
  get 'hysan', to: 'cpanel#index', as: 'hysan'
  resources :hero_images
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # get 'sessions/new'
  get 'signup', to: "users#new"
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hero_image.rb
class HeroImage < ApplicationRecord
  has_many_attached :images
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
    validates :subject, presence: true
    validates :body, presence: true
end

app/models/ourservice.rb
class Ourservice < ApplicationRecord
    has_many_attached :images
    has_many_attached :pdf_files
    belongs_to :user
    validates :Title, presence: true, length: { minimum: 5 }
    validates :description, presence: true, length: { minimum: 10 }

end

app/models/partner.rb
class Partner < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_secure_password
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    format: /\A\S+@\S+\z/

  has_many :hero_images
  has_many :ourservices
  has_many :projects
    def self.authenticate(email, password)
        user = User.find_by(email: email)
        user && user.authenticate(password)
    end

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def self.new_token
      SecureRandom.urlsafe_base64
    end

    def remember 
      self.remember_token = user.new_token
      update_attribute(:remember_digest)
    end


end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @hero_images = HeroImage.all.limit(2)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @hero_images = HeroImage.all
    @ourservices = Ourservice.limit(4)
    @partners = Partner.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/cpanel_helper.rb
module CpanelHelper
end

app/helpers/hero_images_helper.rb
module HeroImagesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ourservices_helper.rb
module OurservicesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/header/_dropdown.html.erb
<ul class="dropdown-menu">
                        <li>
                        <%= link_to 'Item 1', '#', class: "header__menu__item" %>
                        </li>
                        <li>
                        <%= link_to 'Item 2', '#', class: "header__menu__item" %>
                        </li>
                        <li class="dropdown-right">
                            <a href ="#" class="header__menu__item">
                              Item 3 <i class="fas fa-angle-right"></i>
                            </a>
                            <ul class="menu-right">
                              <li><a href="#" class="menu-item">Item3.1</a></li>
                              <li><a href="#" class="menu-item">Item3.2</a></li>
                              <li><a href="#" class="menu-item">Item3.3</a></li>
                              <li><a href="#" class="menu-item">Item3.3</a></li>
                            </ul>
                        </li>
                        <li>
                        <%= link_to 'Item 4', '#', class: "header__menu__item" %>
                        </li>
                    </ul>

app/views/layouts/header/_nav.html.erb
<header class="header-container"  data-controller="humburger">
  <div class="logo-menu">
    <%= image_tag "Kamic.PNG", alt: "Logo" %>
    <button data-action="click->humburger#toggle" class="btn-mobile-nav">
        <i class="fa-solid fa-bars"></i>
        <i class="fa-solid fa-xmark"></i>
    </button>
  </div>
  
  <div class="header">

      <div class="header__top">
        <div class="header__contacts" %>
            <span>
            <i class="fa-solid fa-location-dot"></i> Mkuranga, PWANI, 1949 Tanzania
            </span>
            <span>
            <i class="fa-solid fa-envelope"></i>
             sales@hysan.co.tz
            </span>
            <span>
            <i class="fa-solid fa-phone-volume"></i>
            +(255) 0752443624
            </span>
        </div>
        <div class="menu-container">
            
            <div class="social">
              <a href="https://twitter.com" target="_blank"><i class="fa-brands fa-facebook"></i></a>
              <a href="https://twitter.com" target="_blank"><i class="fa-brands fa-twitter"></i></a>
            </div>
        </div>
      </div>
       <nav>
          <ul class="header__menu"  data-action="click->humburger#removenav">
              <li>
                <%= link_to 'Home', root_path, class: "header__menu__item" %>
              </li>
  
              <li class="mega">
                <%= link_to 'Service', ourservices_path, class: "header__menu__item" %>
              </li>
              <li class="mega">
                <%= link_to 'Company', about_us_path, class: "header__menu__item" %>
              </li>
              <li>
                <%= link_to 'Contact Us', contact_us_path, class: "header__menu__item" %>
              </li>
            <% if current_user %>
              <%= link_to 'Dashboard', hysan_path, class: "btn--dash" %>
              <%= button_to 'logout', logout_path, method: :delete, class: "btn--dash" %>
              <% end %>
            </ul>
       </nav>
  </div>
</header>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <section  id="errors">
      <header>
        <h2>
        Oops! Your form could not be saved.
        </h2>
        <h3>
          Please correct the following 
          <%= pluralize(object.errors.count, "error") %>
        </h3>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
        </ul>
      </header>
    </section>
  <% end %>